import { withModuleId } from "@/lib/course-lesson-builder";

export const moduleThreeTasks = withModuleId("3", [
  {
    id: "3.1",
    title: "Health-check через APIRequestContext",
    summary: "Проверить доступность Notes API без запуска браузера.",
    context: "API-проверка быстрее UI и отделяет доступность backend от состояния браузера.",
    theory: ["APIRequestContext выполняет HTTP-запросы напрямую.", "Notes API root возвращает health response; endpoint строится от NOTES_API_URL."],
    steps: ["Создайте tests/api/health-check.spec.ts.", "Выполните GET на NOTES_API_URL через fixture request.", "Проверьте status 200 и success response.", "Не создавайте browser page для API-only проверки."],
    files: ["tests/api/health-check.spec.ts"],
definitionOfDone: ["Запрос выполняется без браузера.", "Проверяется HTTP 200 через Playwright expect.", "URL берётся из src/config/env.ts."],
    hints: ["Используйте встроенную request fixture.", "Для GET дождитесь response через await.", "Сначала проверьте response.status(), затем разберите JSON только если это нужно."],
    commands: ["npm run test -- tests/api/health-check.spec.ts"],
  },
  {
    id: "3.2",
    title: "Регистрация пользователя через API",
    summary: "Подготовить тестового пользователя запросом POST /users/register.",
    context: "Создание данных через backend устраняет медленные UI-действия там, где интерфейс не является предметом проверки.",
    theory: ["POST передаёт JSON body и может создавать ресурс со статусом 201.", "Внешний JSON нужно проверять по форме, а не безусловно доверять типу."],
    steps: ["Создайте tests/api/user-registration.spec.ts.", "Сгенерируйте TestUser через общую функцию.", "Отправьте POST на users/register, присоединив путь к NOTES_API_URL.", "Проверьте статус, success-поле и минимальные ожидаемые поля ответа."],
    files: ["tests/api/user-registration.spec.ts"],
definitionOfDone: ["Регистрация выполняется APIRequestContext.", "Ожидается 201 Created и валидируется контракт ответа.", "Уникальный email создаётся генератором; пароль не логируется."],
    hints: ["Путь endpoint присоединяйте к NOTES_API_URL, не добавляйте второй домен.", "Playwright request.post принимает data с JSON-совместимым объектом.", "Сначала проверьте статус; JSON можно сузить type guard или явной проверкой полей."],
    commands: ["npm run test -- tests/api/user-registration.spec.ts"],
  },
  {
    id: "3.3",
    title: "Login и безопасное получение токена",
    summary: "Войти по API и передать x-auth-token в защищённый запрос.",
    context: "Notes API защищает пользовательские операции токеном. Его нужно использовать в памяти теста, не записывая в вывод и артефакты.",
    theory: ["Login возвращает токен в контракте ответа или заголовке API.", "Секретный токен не должен попадать в логи, snapshots, Git или отчёты."],
    steps: ["Создайте пользователя через API и дождитесь успешного ответа.", "Выполните POST users/login теми же данными.", "Извлеките x-auth-token согласно фактическому контракту ответа.", "Используйте токен только в заголовке следующего защищённого запроса."],
    files: ["tests/api/user-login.spec.ts"],
definitionOfDone: ["Login использует пользователя текущего прогона.", "Токен доступен в переменной только во время теста.", "Значение токена не печатается и не сохраняется в файл."],
    hints: ["Сначала изучите тело и headers ответа без console.log полного объекта.", "Playwright response.headers() и response.json() позволяют проверить оба источника.", "Передавайте заголовок как `headers: { 'x-auth-token': token }` и никогда не логируйте token."],
    commands: ["npm run test -- tests/api/user-login.spec.ts"],
  },
  {
    id: "3.4",
    title: "Клиент UsersApi",
    summary: "Вынести повторяющиеся registration/login запросы в типизированный API-клиент.",
    context: "После повторного использования одинаковые детали endpoint и заголовков лучше держать в одном клиенте, не превращая каждый тест в набор низкоуровневых запросов.",
    theory: ["API client инкапсулирует транспорт и формат endpoint.", "Assertions и сценарные решения остаются в тесте, клиент отвечает за действие."],
    steps: ["Создайте src/api/users-api.ts с классом UsersApi.", "Передайте APIRequestContext и NOTES_API_URL через constructor.", "Добавьте методы register и login с типами аргументов/ответов.", "Переведите два теста на вызовы клиента и удалите дублирование URL."],
    files: ["src/api/users-api.ts", "tests/api/user-registration.spec.ts", "tests/api/user-login.spec.ts"],
definitionOfDone: ["Регистрация и login инкапсулированы в отдельном клиенте.", "Тесты не собирают endpoint и request.post напрямую.", "Ошибки ответов остаются диагностируемыми."],
    hints: ["Передайте request context извне вместо создания скрытого глобального клиента.", "Сделайте методы async и возвращайте response либо типизированный результат.", "Оставьте expect в тестах, чтобы API-клиент не смешивал действия и проверки."],
    commands: ["npm run test -- tests/api/user-registration.spec.ts tests/api/user-login.spec.ts"],
  },
  {
    id: "3.5",
    title: "Создание заметки через API",
    summary: "Создать защищённую заметку и сохранить её id для дальнейших операций.",
    context: "После освоения auth token ученик создаёт заметку напрямую, передавая минимальное тело запроса и проверяя созданный ресурс.",
    theory: ["Защищённый endpoint требует x-auth-token.", "Серверный id нужно получить из ответа, а не выдумывать в тесте."],
    steps: ["Сгенерируйте пользователя и войдите через UsersApi.", "Подготовьте title, description и category.", "Отправьте POST notes с x-auth-token.", "Проверьте успешный status и сохраните возвращённый id."],
    files: ["tests/api/note-create.spec.ts"],
definitionOfDone: ["Создание выполняется API под токеном нового пользователя.", "Статус соответствует реальному контракту 200/201.", "id извлекается и проверяется как непустая строка."],
    hints: ["Уточните допустимые поля по API contract, не отправляйте лишние свойства.", "Не передавайте токен в URL или body.", "Сначала проверьте response.ok/status, потом считайте JSON и извлеките id."],
    commands: ["npm run test -- tests/api/note-create.spec.ts"],
  },
  {
    id: "3.6",
    title: "CRUD и негативные API-сценарии",
    summary: "Прочитать, изменить, завершить и удалить заметку; проверить 400 и 401.",
    context: "Полезный API client покрывает жизненный цикл ресурса и объясняет поведение backend на валидных и ошибочных запросах.",
    theory: ["Каждая операция проверяет свой контракт и конкретный resource id.", "Негативный тест подтверждает ожидаемую обработку ошибки, а не просто любой неуспех."],
    steps: ["Добавьте в NotesApi методы list/get/update/complete/delete.", "Создайте заметку и пройдите операции по её id: PATCH меняет только completed, PUT обновляет все обязательные поля заметки.", "Добавьте сценарий без токена и сценарий с невалидным телом.", "Проверьте точные ожидаемые статусы и очистите ресурс."],
    files: ["src/api/notes-api.ts", "tests/api/note-crud.spec.ts"],
definitionOfDone: ["CRUD-операции используют типизированный API client.", "401 и 400 проверяются отдельными сценариями.", "Запросы относятся только к данным тестового пользователя."],
    hints: ["Разделите happy path и negative path на понятные test cases.", "Для auth используйте тот же заголовок, что и в задаче 3.3.", "Удаление проверяйте запросом по тому же id; не скрывайте неверный статус широким условием."],
    commands: ["npm run test -- tests/api/note-crud.spec.ts"],
  },
  {
    id: "3.7",
    title: "Гарантированная очистка аккаунта",
    summary: "Удалить только созданный тестом аккаунт даже при падении сценария.",
    context: "Notes API публичный; забытые аккаунты и заметки загрязняют общую SUT. Cleanup должен владеть только учётными данными, созданными самим тестом.",
    theory: ["Teardown выполняется независимо от успешных assertions.", "Удаление аккаунта каскадно убирает заметки и требует его auth token."],
    steps: ["Добавьте cleanup method для DELETE users/delete-account.", "Храните token только в памяти fixture/test.", "Подключите cleanup в afterAll или teardown.", "Спровоцируйте безопасный тестовый fail и убедитесь, что cleanup всё равно запускается."],
    files: ["src/api/users-api.ts", "tests/api/fixtures.ts", "tests/api/user-registration.spec.ts"],
definitionOfDone: ["Удаляется только аккаунт, созданный текущим тестом.", "Cleanup запускается при success и failure.", "Токен не попадает в лог или репозиторий."],
    hints: ["Сохраняйте cleanup данные только после успешной регистрации.", "Используйте try/finally или teardown fixture.", "Если delete завершается ошибкой, сообщите о ней, но не печатайте auth header/token."],
    commands: ["npm run test -- tests/api"],
  },
]);
