import { withModuleId } from "@/lib/course-lesson-builder";

export const moduleSevenTasks = withModuleId("7", [
  {
    id: "7.1",
    title: "Диагностика flaky test",
    summary: "Найти источник нестабильности и убрать фиксированные ожидания.",
    context: "Случайный sleep маскирует причину нестабильности и замедляет каждый прогон. Надёжный тест ждёт конкретное состояние или устраняет конфликт данных.",
    theory: ["Auto-waiting и web-first assertions ждут ожидаемый UI state.", "Повторный запуск без диагностики не исправляет гонку."],
    steps: ["Запустите указанный flaky spec несколько раз.", "Изучите trace, assertion и момент появления элемента.", "Классифицируйте причину: состояние UI, сеть, данные или shared resource.", "Замените waitForTimeout на assertion/event wait и повторите прогон."],
    files: ["tests/ui/flaky.spec.ts"],
definitionOfDone: ["Причина нестабильности записана и устранена.", "В коде нет page.waitForTimeout.", "Тест ожидает конкретное observable state."],
    hints: ["Сначала сохраните фактическую ошибку, не добавляя retry.", "Сверьте таймлайн действия и события в trace.", "Ждите locator state/response/event, который причинно связан с действием."],
    commands: ["npm run test -- tests/ui/flaky.spec.ts --repeat-each=5"],
  },
  {
    id: "7.2",
    title: "Trace, screenshots и video",
    summary: "Настроить сбор диагностических артефактов при повторе и падении.",
    context: "CI падение может быть невоспроизводимо локально. Trace и screenshot позволяют восстановить шаги, состояние страницы и точку ошибки.",
    theory: ["trace: on-first-retry экономит место и сохраняет данные для повторной попытки.", "Артефакты могут содержать персональные данные и должны иметь ограниченный доступ."],
    steps: ["Настройте trace на on-first-retry.", "Настройте screenshot и video только при failure.", "Сделайте локальный контрольный запуск с безопасно падающим тестом.", "Откройте trace viewer и найдите ошибочный шаг; удалите тестовый trigger после проверки."],
    files: ["playwright.config.ts", ".gitignore"],
definitionOfDone: ["Trace, screenshot и video создаются по выбранной failure policy.", "Артефакт можно открыть и связать с упавшим шагом.", "Секретные значения не выводятся и не публикуются."],
    hints: ["Храните настройку в use config.", "Проверьте значение on-first-retry и retain-on-failure.", "Используйте `npx playwright show-trace <trace.zip>` для локального анализа."],
    commands: ["npm run test", "npx playwright show-trace test-results/<trace>.zip"],
  },
  {
    id: "7.3",
    title: "Параллельные workers",
    summary: "Запустить suite в 2–4 workers и устранить конфликты тестовых данных.",
    context: "Параллельный запуск меняет порядок и близость действий. Общие аккаунты и предсказуемые title приводят к конфликтам между тестами.",
    theory: ["worker count управляет количеством параллельных процессов.", "Данные каждого теста должны быть изолированы и очищаться владельцем."],
    steps: ["Запустите подходящий suite с 2 workers, затем с 4.", "Зафиксируйте конфликты ресурсов и привяжите их к тестам.", "Внедрите runId/worker suffix из задачи 5.5.", "Повторите запуск и убедитесь, что данные не пересекаются."],
    files: ["playwright.config.ts", "src/utils/test-data.ts", "tests/fixtures.ts"],
definitionOfDone: ["Выбранные тесты проходят в 2–4 workers.", "Каждый ресурс уникален для test/worker/run.", "Cleanup одного теста не меняет данные другого."],
    hints: ["Сначала запускайте только изолируемый набор.", "Используйте workerInfo и общий runId.", "Не делите одну запись или пользователя между независимыми тестами."],
    commands: ["npx playwright test --workers=2", "npx playwright test --workers=4"],
  },
  {
    id: "7.4",
    title: "fullyParallel и maxFailures",
    summary: "Включить полную параллельность после подтверждённой изоляции.",
    context: "fullyParallel запускает тестовые случаи независимо; включать его до фиксации shared state опасно. maxFailures ограничивает бесполезный прогон при массовом отказе.",
    theory: ["fullyParallel влияет на независимое выполнение тестов внутри файлов.", "maxFailures останавливает запуск после заданного количества ошибок."],
    steps: ["Подтвердите, что предыдущая задача стабильно проходит с несколькими workers.", "Включите fullyParallel.", "Задайте разумный maxFailures и объясните выбор.", "Запустите suite с несколькими workers и сравните итоговое время и ошибки."],
    files: ["playwright.config.ts"],
definitionOfDone: ["fullyParallel включён после проверки изоляции.", "maxFailures задокументирован и ограничивает массовые ошибки.", "Параллельный прогон не создаёт data collisions."],
    hints: ["Не включайте fullyParallel, пока тесты используют общие изменяемые ресурсы.", "Начните с небольшого maxFailures.", "Сравните trace падений до и после включения полной параллельности."],
    commands: ["npx playwright test --workers=4"],
  },
]);