import { withModuleId } from "@/lib/course-lesson-builder";

export const moduleEightTasks = withModuleId("8", [
  {
    id: "8.1",
    title: "Анализ HTML Report",
    summary: "Использовать уже настроенный HTML-отчёт для разбора результата и диагностики падений.",
    context: "HTML reporter уже включён в задаче 0.4. Теперь важна не повторная настройка, а умение читать результат: найти упавший тест, понять assertion, открыть доступный trace или screenshot и отделить проблему сценария от недоступности SUT.",
    theory: ["HTML report группирует результаты, ошибки и прикреплённые диагностические артефакты одного прогона.", "Отчёты и test-results часто содержат локальные данные и должны игнорироваться Git.", "Артефакт помогает локализовать проблему, но не заменяет проверку причины падения."],
    steps: ["Запустите небольшой suite через npm run test и откройте готовый отчёт командой npm run report.", "Найдите в отчёте статус каждого теста, длительность и текст assertion; при намеренном учебном падении не исправляйте тест до определения причины.", "Если доступны trace, screenshot или video, откройте только относящиеся к упавшему тесту артефакты и сравните ожидаемое с наблюдаемым состоянием.", "Добавьте playwright-report и test-results в .gitignore, затем проверьте git status: артефакты не должны попасть в commit."],
    files: [".gitignore"],
definitionOfDone: ["HTML report открыт через существующую команду npm run report.", "Для одного результата ученик может назвать статус, assertion и релевантный артефакт либо объяснить его отсутствие.", "playwright-report и test-results не попадают в Git."],
    hints: ["Не меняйте reporter: он уже настроен в задаче 0.4.", "Начните с общей сводки, затем откройте страницу одного теста и прочитайте error до просмотра артефактов.", "Добавьте в .gitignore отдельными строками playwright-report/ и test-results/, запустите git status и убедитесь, что папки не показаны как untracked."],
    commands: ["npm run test", "npm run report"],
  },
  {
    id: "8.2",
    title: "Allure Report",
    summary: "Добавить Allure как дополнительный формат анализа прогона.",
    context: "Allure полезен для подробного истории шагов и вложений, но не должен дублировать содержимое без причины или перегружать тест шумом.",
    theory: ["Playwright adapter собирает события тестов в Allure results.", "Сырые результаты нужно генерировать заново и игнорировать в Git."],
    steps: ["Установите совместимый allure-playwright adapter и CLI по официальной инструкции.", "Добавьте reporter config.", "Добавьте смысловые steps и только полезные attachments.", "Запустите небольшой suite, соберите и откройте отчёт."],
    files: ["package.json", "package-lock.json", "playwright.config.ts", ".gitignore"],
definitionOfDone: ["Allure results собираются для выполненных тестов.", "Отчёт показывает шаги и релевантные артефакты.", "Личные данные и секреты не прикладываются."],
    hints: ["Сначала проверьте совместимость версии adapter с установленным Playwright.", "Добавляйте шаги на бизнес-действиях, не на каждом locator call.", "Сравните report с HTML reporter и удалите дублирующий шум."],
    commands: ["npm run test", "npx allure generate allure-results --clean"],
  },
  {
    id: "8.3",
    title: "GitHub Actions: Smoke",
    summary: "Запускать короткий smoke suite при push и pull request.",
    context: "CI показывает, воспроизводится ли базовая проверка в чистом Linux runner без локального состояния разработчика.",
    theory: ["Workflow задаёт trigger, runner и последовательность reproducible steps.", "Браузерные зависимости и репорты должны быть установлены/сохранены явно."],
    steps: ["Создайте .github/workflows/smoke.yml.", "Добавьте checkout, setup-node с cache и npm ci.", "Установите только нужный browser и system dependencies.", "Запустите smoke tag и сохраните report/trace при failure."],
    files: [".github/workflows/smoke.yml", ".gitignore"],
definitionOfDone: ["Workflow запускается на push и pull_request.", "Он устанавливает lockfile зависимости и браузер.", "При failure сохраняются диагностические артефакты без secret values."],
    hints: ["Воспроизводите локальные npm команды, не используйте npm install в CI.", "Ограничьте путь upload artifact на report/test-results.", "Не публикуйте storageState, env files или auth headers в artifact."],
    commands: ["npm run test -- --grep @smoke"],
  },
  {
    id: "8.4",
    title: "Nightly regression",
    summary: "Запланировать регресс с retry и понятной классификацией сбоев.",
    context: "Ночной прогон может упасть из-за продукта, SUT недоступности или инфраструктуры. Эти причины требуют разных действий и сообщений.",
    theory: ["schedule использует cron UTC и должен иметь ручной workflow_dispatch для диагностики.", "Retry policy не превращает flaky тест в pass без анализа первого сбоя."],
    steps: ["Добавьте расписание и ручной запуск в regression workflow.", "Запускайте полный regression tag с ограниченным retry policy.", "Разделите health-check/SUT availability failure и product assertions.", "Сохраняйте trace и сводку статусов, удаляя секретные данные."],
    files: [".github/workflows/nightly.yml", "playwright.config.ts"],
definitionOfDone: ["Workflow запускается по расписанию и вручную.", "Retry limit определён и не скрывает flaky результат.", "Инфраструктурные и продуктовые ошибки различимы."],
    hints: ["Cron в GitHub Actions интерпретируется в UTC.", "Используйте отдельный лёгкий SUT health step перед suite.", "Не игнорируйте failed-first/passed-retry статистику."],
    commands: ["npx playwright test --grep @regression"],
  },
  {
    id: "8.5",
    title: "Sharding и объединённый отчёт",
    summary: "Разделить suite на два shard и собрать общий blob report.",
    context: "Sharding сокращает время большого suite на CI за счёт нескольких runners, но для анализа нужен один объединённый отчёт.",
    theory: ["--shard=i/n выбирает часть тестов.", "blob reporter создаёт входные данные для merge-reports."],
    steps: ["Создайте два matrix jobs с shard 1/2 и 2/2.", "Сохраняйте blob report каждого shard как artifact.", "Добавьте merge job, скачивающий оба artifact.", "Соберите единый HTML report и проверьте число тестов."],
    files: [".github/workflows/regression.yml"],
definitionOfDone: ["Оба shard завершаются с независимыми результатами.", "Blob artifacts загружаются и объединяются.", "Итоговый HTML содержит тесты обоих shard ровно по одному разу."],
    hints: ["Используйте strategy.matrix для индекса shard.", "Каждый job должен публиковать blob report даже при failure.", "В merge job скачайте все artifacts в одну папку до `npx playwright merge-reports --reporter html`."],
    commands: ["npx playwright test --shard=1/2", "npx playwright test --shard=2/2"],
  },
  {
    id: "8.6",
    title: "Масштабирование: Sharding и Allure Report",
    summary: "Учимся распараллеливать тесты на нескольких CI-воркерах и собирать единый Allure-отчет.",
    context: "С ростом количества тестов один воркер в GitHub Actions перестает справляться, и прогон занимает слишком много времени. Playwright поддерживает Sharding — разделение тестов на части для параллельного запуска на разных машинах. После такого прогона нужно правильно объединить артефакты и сгенерировать красивый Allure-отчет.",
    theory: [
      "Sharding позволяет запустить тесты командой `--shard=1/3`.",
      "GitHub Actions умеет создавать матрицу задач (matrix jobs) для одновременного запуска шардов.",
      "Артефакты (blob-репорты, allure-results) скачиваются в одну папку с разных воркеров, после чего генерируется единый отчёт.",
    ],
    steps: [
      "Настроить стратегию matrix в GitHub Actions для запуска 3 шардов.",
      "Изменить команду запуска тестов на использование `--shard=${{ matrix.shard }}/${{ strategy.job-total }}`.",
      "Настроить загрузку артефактов (upload-artifact) с каждого шарда.",
      "Добавить job для объединения артефактов (download-artifact) и генерации Allure Report.",
      "Опубликовать Allure Report через GitHub Pages.",
    ],
    files: [".github/workflows/regression.yml"],
    definitionOfDone: [
      "Matrix strategy создаёт 3 параллельных shard job.",
      "Каждый shard загружает свои артефакты.",
      "Единый Allure Report собирается и публикуется через GitHub Pages.",
    ],
    hints: [
      "Используйте `strategy: matrix: shard: [1/3, 2/3, 3/3]` для деления.",
      "Каждый job должен публиковать артефакт даже при failure (`if: always()`).",
      "В merge job скачайте все artifacts в одну папку перед генерацией отчёта.",
    ],
    commands: ["npx playwright test --shard=1/3", "npx allure generate allure-results --clean"],
  },
  {
    id: "8.7",
    title: "Сводка результатов в GitHub Actions",
    summary: "Вывести безопасную сводку прогона прямо на страницу GitHub Actions.",
    context: "Для первой CI-сводки не нужны Telegram, Slack, webhook и дополнительные секреты. GitHub Actions показывает результат прямо на странице запуска через Job Summary.",
    theory: [
      "GITHUB_STEP_SUMMARY — специальный файл, который GitHub отображает в итогах job.",
      "Шаг с if: always() выполняется и после успеха, и после ошибки.",
      "Сводка не должна содержать токены, email, webhook URL и сырые тексты ошибок.",
    ],
    steps: [
      "Добавить финальный step в CI-пайплайн с `if: always()`.",
      "Записать в GITHUB_STEP_SUMMARY статус job и ссылку на скачиваемый отчётный artifact.",
      "Убедиться, что в текст не попали токены, webhook URL, email и сырые ошибки.",
      "Запустить workflow и открыть вкладку Summary на странице GitHub Actions.",
    ],
    files: [".github/workflows/regression.yml"],
    definitionOfDone: [
      "После завершения CI на странице job видна понятная сводка.",
      "Сводка содержит статус и ссылку на отчётный artifact.",
      "Секреты и персональные данные не попадают в Summary и логи.",
    ],
    hints: [
      "Используйте `if: always()`, иначе Summary будет пропущен при failure.",
      "Пишите Markdown в переменную GITHUB_STEP_SUMMARY, а не в сторонний API.",
      "Сначала добавьте только статус и ссылку на artifact; подробности остаются в отчёте.",
    ],
    commands: ["npm run test -- --grep @regression"],
  },
]);
