import type { CourseLesson } from "@/lib/module-zero";

export const moduleOneTasks: CourseLesson[] = [
  {
    moduleId: "1", id: "1.1", slug: "1-1", title: "Первый UI-тест и поиск локатора",
    summary: "Открыть стенд, самостоятельно найти ссылку в Inspector и проверить результат перехода.",
    context: "Тест не может кликнуть «просто куда-то»: ему нужен точный и понятный адрес элемента — локатор. Inspector помогает увидеть, как Playwright находит реальный элемент. Это решает проблему хрупких догадок и копирования CSS-классов из чужого кода.",
    theory: ["page управляет вкладкой браузера.", "Playwright Inspector показывает, какой элемент выбран и какое доступное имя видит браузер.", "getByRole описывает элемент так, как его воспринимает пользователь: ссылка, кнопка или заголовок.", "expect превращает сценарий действий в тест с проверяемым результатом."],
    steps: ["Создайте tests/sandbox.spec.ts и откройте стенд через await page.goto('/').", "Запустите тест в режиме Inspector: npx playwright test --debug tests/sandbox.spec.ts.", "Наведите Inspector на настоящую ссылку Web inputs и запишите роль и доступное имя, которые он показывает.", "Вставьте найденный локатор вместо отмеченного места в коде и кликните по нему.", "Тем же способом найдите заголовок открывшейся страницы и подтвердите его через expect(...).toBeVisible()."],
    files: ["tests/sandbox.spec.ts"], definitionOfDone: ["В тест вставлены локаторы реальных элементов страницы.", "Переход и заголовок подтверждены проверкой."],
    hints: ["Импортируйте test и expect.", "Перед действием браузера ставьте await.", "Сначала выбирайте getByRole, затем getByLabel и только потом data-testid."], commands: ["npx playwright test --debug tests/sandbox.spec.ts"],
  },
  {
    moduleId: "1", id: "1.2", slug: "1-2", title: "Локаторы и ввод текста",
    summary: "Заполнить настоящую форму Web inputs по доступным подписям и проверить результат.",
    context: "Поле формы лучше искать по подписи, которую видит человек, а не по техническому CSS-классу. Так тест понятнее и устойчивее к изменениям вёрстки.",
    theory: ["getByLabel находит поле по подписи.", "fill очищает поле и вводит новый текст.", "После действия проверяем видимый результат, а не только факт клика."],
    steps: ["Откройте /inputs.", "Заполните Input: Text и Input: Password через getByLabel.", "Нажмите Display Inputs через getByRole.", "Проверьте отображение введённого текста через getByText."],
    files: ["tests/sandbox.spec.ts"], definitionOfDone: ["Оба поля заполнены через getByLabel.", "Введённый текст подтверждён expect."],
    hints: ["Сначала найдите видимую подпись поля.", "Не используйте CSS-селекторы для этих полей.", "Сравните свой тест с эталоном."], commands: ["npx playwright test tests/sandbox.spec.ts"],
  },
  {
    moduleId: "1", id: "1.3", slug: "1-3", title: "Async / await: первый API-тест",
    summary: "Отправить health-check к Notes API и дождаться ответа сервера.",
    context: "Сервер отвечает не мгновенно. await говорит тесту: «сначала дождись ответа, затем читай и проверяй его».",
    theory: ["Promise — обещание будущего результата.", "async разрешает использовать await внутри функции.", "request — готовый инструмент Playwright для API-запросов без открытия браузера."],
    steps: ["Создайте tests/api/health-check.spec.ts.", "Импортируйте test и expect.", "Отправьте await request.get('/notes/api') и сохраните ответ в response.", "Проверьте успешность ответа и поле success из JSON."],
    files: ["tests/api/health-check.spec.ts"], definitionOfDone: ["У API-запроса есть await.", "Статус и JSON-ответ подтверждены через expect."],
    hints: ["Сначала дождитесь response.", "JSON читается отдельным await response.json().", "Не выводите весь ответ в консоль."], commands: ["npx playwright test tests/api/health-check.spec.ts"],
  },
  {
    moduleId: "1", id: "1.4", slug: "1-4", title: "Promise.all для независимых запросов",
    summary: "Одновременно проверить главную страницу и Notes API.",
    context: "Два независимых запроса можно начать вместе. Но действия в одной вкладке браузера должны оставаться последовательными: ей нельзя одновременно открыть две страницы.",
    theory: ["Promise.all ждёт завершения нескольких Promise.", "Результаты возвращаются в том же порядке, что и запросы.", "Если один запрос упал, вся группа сообщает об ошибке."],
    steps: ["Откройте health-check из прошлого урока.", "Создайте Promise.all с request.get('/') и request.get('/notes/api').", "Сохраните два ответа в две переменные.", "Отдельно подтвердите успешность каждого ответа."],
    files: ["tests/api/health-check.spec.ts"], definitionOfDone: ["Два независимых запроса выполняются через Promise.all.", "У каждого ответа есть собственная проверка."],
    hints: ["Не используйте Promise.all для двух page.goto.", "Порядок переменных соответствует порядку запросов.", "Проверьте оба ответа, а не только первый."], commands: ["npx playwright test tests/api/health-check.spec.ts"],
  },
  {
    moduleId: "1", id: "1.5", slug: "1-5", title: "Адреса стенда в одном месте",
    summary: "Вынести UI и API адреса в типизированный модуль окружения.",
    context: "Когда адрес записан в десятках тестов, его сложно безопасно изменить. Один модуль конфигурации даёт тестам единый источник адресов.",
    theory: ["process.env читает настройки окружения.", "Оператор ?? задаёт безопасное учебное значение по умолчанию.", "new URL аккуратно собирает адрес API от BASE_URL."],
    steps: ["Откройте src/config/env.ts.", "Создайте BASE_URL с учебным значением Expand Testing по умолчанию.", "Создайте NOTES_API_URL через new URL('/notes/api', BASE_URL).toString().", "Используйте относительные пути в page.goto и request.get после настройки baseURL."],
    files: ["src/config/env.ts", "playwright.config.ts"], definitionOfDone: ["BASE_URL и NOTES_API_URL экспортируются из одного файла.", "Тесты не содержат полный домен в page.goto."],
    hints: ["Не создавайте отдельный URL для каждой страницы.", "API-путь строится от BASE_URL.", "Сохраните полный домен только в настройках."], commands: ["npx tsc --noEmit"],
  },
  {
    moduleId: "1", id: "1.6", slug: "1-6", title: "Типы данных TestUser и Note",
    summary: "Описать форму тестового пользователя и заметки до их использования в API-тестах.",
    context: "TypeScript ловит ошибку в имени поля ещё в редакторе. Для этого ему нужна понятная «анкета» данных — interface.",
    theory: ["interface описывает обязательные поля объекта.", "string — текстовое значение, boolean — true или false.", "export позволяет импортировать тип из другого файла."],
    steps: ["Создайте src/types/test-data.ts.", "Опишите TestUser с name, email и password типа string.", "Опишите Note с id, title, description, category и completed.", "Запустите проверку типов без открытия браузера."],
    files: ["src/types/test-data.ts"], definitionOfDone: ["TestUser и Note экспортируются.", "npx tsc --noEmit проходит без ошибок."],
    hints: ["После имени поля поставьте двоеточие и тип.", "Строки в interface заканчиваются точкой с запятой.", "Не используйте any для обхода ошибок типов."], commands: ["npx tsc --noEmit"],
  },
  {
    moduleId: "1", id: "1.7", slug: "1-7", title: "Безопасное окружение: .env",
    summary: "Отделить локальные настройки от кода и не отправить их в Git.",
    context: "Файл .env принадлежит компьютеру ученика. В репозиторий попадает только .env.example — безопасная памятка с названиями переменных.",
    theory: [".env хранит локальные настройки и секреты.", ".env.example содержит названия переменных без настоящих значений.", ".gitignore не даёт Git добавить локальный .env."],
    steps: ["Создайте .env.example с BASE_URL.", "Создайте локальный .env по этому образцу.", "Убедитесь, что .env указан в .gitignore.", "Проверьте git status: локальный файл не должен появиться среди изменений."],
    files: [".env.example", ".gitignore", "src/config/env.ts"], definitionOfDone: [".env.example не содержит секретов.", ".env игнорируется Git.", "Конфигурация читает BASE_URL через process.env."],
    hints: ["Не публикуйте пароль или токен в .env.example.", "Проверьте игнорирование командой git check-ignore .env.", "Не добавляйте префикс NEXT_PUBLIC_ к секретам."], commands: ["git check-ignore .env", "npx tsc --noEmit"],
  },
  {
    moduleId: "1", id: "1.8", slug: "1-8", title: "DTO Notes API",
    summary: "Описать типы запроса и ответа Notes API перед созданием API-клиента.",
    context: "DTO — это договор о форме данных на границе с API. Он помогает не перепутать поля при регистрации пользователя и создании заметки.",
    theory: ["DTO описывает данные, которые пересекают границу приложения и API.", "type подходит для составных и объединённых типов.", "Тип не проверяет сервер сам по себе, поэтому API-тест всё равно нужен."],
    steps: ["Создайте src/types/notes-api.ts.", "Опишите RegisterUserDto и CreateNoteDto.", "Опишите безопасный тип ответа без пароля и токена.", "Импортируйте тип в API-тест и выполните проверку TypeScript."],
    files: ["src/types/notes-api.ts", "tests/api/register.spec.ts"], definitionOfDone: ["DTO отражают поля Notes API.", "В типах не хранится настоящий пароль или токен."],
    hints: ["Начните с полей, которые реально отправляются в data.", "Не добавляйте any.", "Название DTO должно объяснять, для какого действия оно нужно."], commands: ["npx tsc --noEmit"],
  },
  {
    moduleId: "1", id: "1.9", slug: "1-9", title: "Generics и фабрика тестовых данных",
    summary: "Создать типизированную фабрику, которая меняет только нужные поля тестовых данных.",
    context: "Фабрика даёт безопасные значения по умолчанию, а overrides позволяет поменять одно поле без копирования всего объекта.",
    theory: ["Generic T сохраняет тип данных, с которым работает функция.", "Partial<T> делает поля необязательными.", "Omit<T, K> создаёт тип без указанных полей."],
    steps: ["Создайте src/utils/user-factory.ts.", "Примите overrides типа Partial<TestUser>.", "Верните полный TestUser, соединив значения по умолчанию и overrides.", "Создайте пользователя с другим name и проверьте типы."],
    files: ["src/utils/user-factory.ts", "src/types/test-data.ts"], definitionOfDone: ["Фабрика возвращает TestUser.", "Overrides меняет одно поле без any.", "npx tsc --noEmit проходит."],
    hints: ["Сначала создайте объект по умолчанию.", "Overrides добавляйте после значений по умолчанию.", "Пароль должен оставаться учебным, а не реальным."], commands: ["npx tsc --noEmit"],
  },
];
