import { withModuleId } from "@/lib/course-lesson-builder";

export const moduleEightTasks = withModuleId("8", [
  {
    id: "8.1",
    title: "HTML Report",
    summary: "Настроить локальную HTML-отчётность Playwright.",
    context: "Краткий терминальный результат помогает быстро увидеть итог, а HTML report позволяет изучить каждый тест, ошибку и артефакт.",
    theory: ["Built-in html reporter создаёт автономный отчёт.", "Отчёты и test-results часто содержат локальные данные и должны игнорироваться Git."],
    steps: ["Настройте reporter html в playwright.config.ts.", "Добавьте npm script для открытия последнего отчёта.", "Запустите suite и откройте report.", "Убедитесь, что report output исключён из Git."],
    files: ["playwright.config.ts", "package.json", ".gitignore"],
    definitionOfDone: ["HTML report создаётся после запуска.", "Есть короткая команда для локального открытия.", "Сгенерированные результаты не попадают в Git."],
    hints: ["Используйте встроенный reporter, не добавляйте зависимость для базового HTML.", "Для просмотра служит `npx playwright show-report`.", "Проверьте git status после запуска и добавьте точный output directory в .gitignore."],
    checkpoint: "chore(report): configure HTML report and local view script",
    commands: ["npm run test", "npm run report"],
  },
  {
    id: "8.2",
    title: "Allure Report",
    summary: "Добавить Allure как дополнительный формат анализа прогона.",
    context: "Allure полезен для подробного истории шагов и вложений, но не должен дублировать содержимое без причины или перегружать тест шумом.",
    theory: ["Playwright adapter собирает события тестов в Allure results.", "Сырые результаты нужно генерировать заново и игнорировать в Git."],
    steps: ["Установите совместимый allure-playwright adapter и CLI по официальной инструкции.", "Добавьте reporter config.", "Добавьте смысловые steps и только полезные attachments.", "Запустите небольшой suite, соберите и откройте отчёт."],
    files: ["package.json", "package-lock.json", "playwright.config.ts", ".gitignore"],
    definitionOfDone: ["Allure results собираются для выполненных тестов.", "Отчёт показывает шаги и релевантные артефакты.", "Личные данные и секреты не прикладываются."],
    hints: ["Сначала проверьте совместимость версии adapter с установленным Playwright.", "Добавляйте шаги на бизнес-действиях, не на каждом locator call.", "Сравните report с HTML reporter и удалите дублирующий шум."],
    checkpoint: "feat(report): integrate allure-playwright and attachments",
    commands: ["npm run test", "npx allure generate allure-results --clean"],
  },
  {
    id: "8.3",
    title: "GitHub Actions: Smoke",
    summary: "Запускать короткий smoke suite при push и pull request.",
    context: "CI показывает, воспроизводится ли базовая проверка в чистом Linux runner без локального состояния разработчика.",
    theory: ["Workflow задаёт trigger, runner и последовательность reproducible steps.", "Браузерные зависимости и репорты должны быть установлены/сохранены явно."],
    steps: ["Создайте .github/workflows/smoke.yml.", "Добавьте checkout, setup-node с cache и npm ci.", "Установите только нужный browser и system dependencies.", "Запустите smoke tag и сохраните report/trace при failure."],
    files: [".github/workflows/smoke.yml", ".gitignore"],
    definitionOfDone: ["Workflow запускается на push и pull_request.", "Он устанавливает lockfile зависимости и браузер.", "При failure сохраняются диагностические артефакты без secret values."],
    hints: ["Воспроизводите локальные npm команды, не используйте npm install в CI.", "Ограничьте путь upload artifact на report/test-results.", "Не публикуйте storageState, env files или auth headers в artifact."],
    checkpoint: "ci: add GitHub Actions workflow for smoke suite",
    commands: ["npm run test -- --grep @smoke"],
  },
  {
    id: "8.4",
    title: "Nightly regression",
    summary: "Запланировать регресс с retry и понятной классификацией сбоев.",
    context: "Ночной прогон может упасть из-за продукта, SUT недоступности или инфраструктуры. Эти причины требуют разных действий и сообщений.",
    theory: ["schedule использует cron UTC и должен иметь ручной workflow_dispatch для диагностики.", "Retry policy не превращает flaky тест в pass без анализа первого сбоя."],
    steps: ["Добавьте расписание и ручной запуск в regression workflow.", "Запускайте полный regression tag с ограниченным retry policy.", "Разделите health-check/SUT availability failure и product assertions.", "Сохраняйте trace и сводку статусов, удаляя секретные данные."],
    files: [".github/workflows/nightly.yml", "playwright.config.ts"],
    definitionOfDone: ["Workflow запускается по расписанию и вручную.", "Retry limit определён и не скрывает flaky результат.", "Инфраструктурные и продуктовые ошибки различимы."],
    hints: ["Cron в GitHub Actions интерпретируется в UTC.", "Используйте отдельный лёгкий SUT health step перед suite.", "Не игнорируйте failed-first/passed-retry статистику."],
    checkpoint: "ci: configure nightly regression and retry policies",
    commands: ["npx playwright test --grep @regression"],
  },
  {
    id: "8.5",
    title: "Sharding и объединённый отчёт",
    summary: "Разделить suite на два shard и собрать общий blob report.",
    context: "Sharding сокращает время большого suite на CI за счёт нескольких runners, но для анализа нужен один объединённый отчёт.",
    theory: ["--shard=i/n выбирает часть тестов.", "blob reporter создаёт входные данные для merge-reports."],
    steps: ["Создайте два matrix jobs с shard 1/2 и 2/2.", "Сохраняйте blob report каждого shard как artifact.", "Добавьте merge job, скачивающий оба artifact.", "Соберите единый HTML report и проверьте число тестов."],
    files: [".github/workflows/regression.yml"],
    definitionOfDone: ["Оба shard завершаются с независимыми результатами.", "Blob artifacts загружаются и объединяются.", "Итоговый HTML содержит тесты обоих shard ровно по одному разу."],
    hints: ["Используйте strategy.matrix для индекса shard.", "Каждый job должен публиковать blob report даже при failure.", "В merge job скачайте все artifacts в одну папку до `npx playwright merge-reports --reporter html`."],
    checkpoint: "ci: configure test sharding and merge blob reports",
    commands: ["npx playwright test --shard=1/2", "npx playwright test --shard=2/2"],
  },
]);