import type { CourseLesson } from "@/lib/module-zero";

export const moduleOneTasks: CourseLesson[] = [
  {
    moduleId: "1",
    id: "1.1",
    slug: "1-1",
    title: "Типы TestUser и Note",
    summary: "Описать форму данных, которыми пользуются автотесты.",
    context:
      "Тестовые сценарии передают пользователя и заметку через несколько слоёв кода. Без явного контракта опечатка в имени поля обнаруживается только во время прогона; типы позволяют поймать её раньше.",
    theory: [
      "Интерфейс TypeScript задаёт обязательные поля объекта на этапе разработки.",
      "Типизация не заменяет runtime-проверку внешнего JSON: ответ API может не соответствовать интерфейсу.",
      "Не используйте any для обхода ошибок типов; уточняйте форму данных.",
    ],
    steps: [
      "Установите TypeScript и типы Node.js как devDependencies.",
      "Создайте tsconfig.json со strict: true и включите каталоги src и tests.",
      "Создайте src/types/test-data.ts.",
      "Опишите и экспортируйте TestUser с полями name, email и password.",
      "Опишите и экспортируйте Note с полями id, title, description, category и completed.",
      "Создайте по одному корректному объекту и проверьте проект командой tsc --noEmit.",
    ],
    files: ["package.json", "package-lock.json", "tsconfig.json", "src/types/test-data.ts"],
    definitionOfDone: [
      "TestUser и Note экспортируются из отдельного файла типов.",
      "Корректные объекты принимаются TypeScript, неизвестные поля дают compile-time ошибку.",
      "В учебном коде не используется any.",
    ],
    hints: [
      "Начните с вопроса: какие поля нужны каждому тестовому пользователю и заметке?",
      "Создайте отдельные interface и назначьте примитивные типы string/boolean.",
      "Для Note.completed используйте boolean, а id пока оставьте строкой: API создаст его позже.",
    ],
    checkpoint: "feat(types): define TestUser and Note interfaces",
    commands: ["npm install --save-dev typescript @types/node", "npx tsc --noEmit"],
  },
  {
    moduleId: "1",
    id: "1.2",
    slug: "1-2",
    title: "Уникальные тестовые данные",
    summary: "Создать типизированный генератор пользователя с уникальным email.",
    context:
      "Параллельные и повторные прогоны не должны пытаться зарегистрировать один email. Уникальный идентификатор изолирует данные запусков и снижает случайные конфликты.",
    theory: [
      "Template literal собирает строку из постоянных частей и динамических значений.",
      "UUID имеет существенно меньший риск коллизии, чем короткий timestamp.",
      "Генератор данных возвращает объект известного типа, а не неструктурированный набор аргументов.",
    ],
    steps: [
      "Создайте src/utils/test-data.ts и импортируйте TestUser из файла типов.",
      "Создайте функцию generateTestUser, которая получает новый UUID для каждого вызова.",
      "Соберите email через template literal и верните объект с именем, email и тестовым паролем.",
      "Создайте два пользователя и сравните их email, не выводя пароль в логи.",
      "Проверьте тип результата командой tsc --noEmit.",
    ],
    files: ["src/utils/test-data.ts", "src/types/test-data.ts"],
    definitionOfDone: [
      "Функция возвращает объект, совместимый с TestUser.",
      "Каждый вызов создаёт отличный email.",
      "Пароль и другие чувствительные поля не печатаются в консоль и не коммитятся как реальные credentials.",
    ],
    hints: [
      "Не передавайте сгенерированное значение извне: функция должна сама создавать уникальный suffix.",
      "В Node.js UUID можно получить стандартным randomUUID из node:crypto.",
      "Соберите адрес по форме `user-${randomUUID()}@example.test` и верните его внутри TestUser.",
    ],
    checkpoint: "feat(utils): add unique user data generator",
    commands: ["npx tsc --noEmit"],
  },
  {
    moduleId: "1",
    id: "1.3",
    slug: "1-3",
    title: "Асинхронность и health-check",
    summary: "Дождаться ответа Notes API и проверить его без пропущенного await.",
    context:
      "Сетевой ответ приходит позже вызова. Если не дождаться Promise, тест может завершиться до получения результата или начать проверять не сам ответ, а объект Promise.",
    theory: [
      "async-функция всегда возвращает Promise.",
      "await приостанавливает текущую async-функцию, но не блокирует весь процесс Node.js.",
      "Корень NOTES API сам служит health-check и возвращает JSON со свойством success.",
    ],
    steps: [
      "Создайте tests/api/health-check.spec.ts.",
      "Используйте APIRequestContext fixture request, не открывая браузерную страницу.",
      "Отправьте GET на Notes API root, выведя адрес из BASE_URL.",
      "Дождитесь response, проверьте HTTP success и JSON-поле success.",
      "Запустите только новый health-check spec и разберите результат.",
    ],
    files: ["tests/api/health-check.spec.ts", "src/config/env.ts"],
    definitionOfDone: [
      "Запрос завершается до assertions; у каждого сетевого Promise есть await.",
      "Тест проверяет HTTP-статус и тело ответа Notes API.",
      "Для запроса используется только утверждённая SUT.",
    ],
    hints: [
      "Сначала запишите последовательность: запрос → response → JSON → assertions.",
      "Playwright fixture request имеет метод get; его результат нужно await-ить.",
      "API root можно получить как new URL('/notes/api', BASE_URL).toString(); тело ответа типизируйте без any.",
    ],
    checkpoint: "test(api): implement async health-check",
    commands: ["npm run test -- tests/api/health-check.spec.ts"],
  },
  {
    moduleId: "1",
    id: "1.4",
    slug: "1-4",
    title: "Параллельные независимые запросы",
    summary: "Сократить ожидание двух независимых health-check через Promise.all.",
    context:
      "Независимые проверки UI и API можно выполнять одновременно. Но параллельные действия через один объект page создают гонку: навигации и состояние вкладки могут конфликтовать.",
    theory: [
      "Promise.all запускает ожидание нескольких Promise одновременно и возвращает результаты в исходном порядке.",
      "Если один Promise отклоняется, Promise.all тоже отклоняется.",
      "Параллелить допустимо независимые HTTP-запросы; последовательные действия одного page должны оставаться последовательными.",
    ],
    steps: [
      "Откройте health-check spec из задачи 1.3.",
      "Подготовьте два независимых GET: главную страницу Expand Testing и корень Notes API.",
      "Запустите оба запроса через Promise.all и дождитесь пары ответов одним await.",
      "Отдельно проверьте оба статуса и данные API.",
      "Сравните структуру с последовательным вариантом и оставьте только обоснованную оптимизацию.",
    ],
    files: ["tests/api/health-check.spec.ts"],
    definitionOfDone: [
      "Оба независимых запроса находятся внутри одного Promise.all.",
      "Проверяется результат каждого запроса; ошибка одного не маскируется.",
      "Promise.all не применяется к двум навигациям или действиям одного page.",
    ],
    hints: [
      "Независимость означает, что второй запрос не использует результат первого.",
      "Promise.all принимает массив Promise и возвращает массив результатов того же порядка.",
      "Используйте `const [siteResponse, apiResponse] = await Promise.all([request.get(BASE_URL), request.get(apiUrl)])`.",
    ],
    checkpoint: "refactor(api): optimize independent requests with Promise.all",
    commands: ["npm run test -- tests/api/health-check.spec.ts"],
  },
  {
    moduleId: "1",
    id: "1.5",
    slug: "1-5",
    title: "Типизированная конфигурация URL",
    summary: "Перенести BASE_URL и NOTES_API_URL в единый модуль конфигурации.",
    context:
      "Когда адреса SUT разбросаны по тестам, смена окружения требует искать и менять множество строк. Один типизированный модуль делает адреса явными и позволяет тестам использовать относительные пути.",
    theory: [
      "process.env содержит строки либо undefined; TypeScript не гарантирует наличие значения во время запуска.",
      "new URL помогает корректно присоединить API path к базовому адресу.",
      "Тесты должны импортировать URL-константы и не хранить домены напрямую.",
    ],
    steps: [
      "Измените src/config/env.ts, сохранив один экспорт BASE_URL.",
      "Добавьте NOTES_API_URL, выводимый из BASE_URL и пути /notes/api.",
      "Замените сборку API URL в health-check spec на импорт NOTES_API_URL.",
      "Убедитесь, что в тестах больше не осталось адресов и путей SUT.",
      "Запустите health-check и общий поиск по тестам на домены.",
    ],
    files: ["src/config/env.ts", "tests/api/health-check.spec.ts"],
    definitionOfDone: [
      "BASE_URL и NOTES_API_URL экспортируются из одного типизированного модуля.",
      "API URL строится из BASE_URL, без второго hardcoded origin.",
      "Тесты используют импорты конфигурации и проходят.",
    ],
    hints: [
      "Сначала найдите повторяющиеся адреса поиском по тестам.",
      "new URL('/notes/api', BASE_URL) нормализует завершающий slash.",
      "Экспортируйте строковое значение через `.toString()` и замените локальную сборку URL импортом NOTES_API_URL.",
    ],
    checkpoint: "chore(config): introduce typed environment configuration",
    commands: ["npm run test -- tests/api/health-check.spec.ts"],
  },
  {
    moduleId: "1",
    id: "1.6",
    slug: "1-6",
    title: "Безопасность и валидация окружения",
    summary: "Добавить .env.example, исключить локальный .env и валидировать обязательные адреса.",
    context:
      "Конфигурация должна быть воспроизводимой, но личные и секретные значения не должны попадать в Git. Безопасный пример документирует имена переменных, а ранняя валидация объясняет недостающую настройку до старта тестов.",
    theory: [
      ".env.example содержит безопасные значения-примеры; .env хранится только локально.",
      "dotenv загружает локальный файл в process.env перед созданием Playwright config.",
      "Ошибка конфигурации должна называть отсутствующую переменную, но не печатать её секретное значение.",
    ],
    steps: [
      "Добавьте dotenv как devDependency и подключите dotenv/config перед чтением env в Playwright config.",
      "Создайте .env.example с BASE_URL и NOTES_API_URL, используя публичные адреса SUT.",
      "Скопируйте его в локальный .env и проверьте, что .env игнорируется Git.",
      "Обновите src/config/env.ts: при отсутствии обязательного URL выбрасывайте понятную ошибку с именем переменной.",
      "Запустите конфиг с корректной средой, затем временно удалите одну обязательную переменную и проверьте fail-fast сообщение.",
    ],
    files: [".env.example", ".gitignore", ".env (локальный, не коммитить)", "package.json", "playwright.config.ts", "src/config/env.ts"],
    definitionOfDone: [
      "Шаблон содержит только имена и публичные URL; реальный .env не отслеживается Git.",
      "Оба обязательных URL валидируются до старта тестов.",
      "При пропуске переменной сообщение называет её имя и не печатает значения окружения.",
    ],
    hints: [
      "Проверьте git check-ignore .env и отдельно убедитесь, что .env.example остаётся отслеживаемым.",
      "Для обязательной строки проверьте значение на undefined/пустую строку до new URL().",
      "Сделайте небольшую helper-функцию readRequiredUrl(name), возвращающую нормализованный URL или ошибку `Missing required environment variable: ${name}`.",
    ],
    checkpoint: "security: add .env.example, gitignore rules and environment validation",
    commands: ["cp .env.example .env", "git check-ignore .env", "npm run test"],
  },
];