import { withModuleId } from "@/lib/course-lesson-builder";

export const moduleFiveTasks = withModuleId("5", [
  {
    id: "5.1",
    title: "LoginPage без лишних абстракций",
    summary: "Инкапсулировать локаторы и действия формы входа.",
    context: "Когда одинаковый login flow начинает повторяться, изменения полей должны требовать правки одного места, но assertions остаются ответственностью теста.",
    theory: ["Page Object представляет действия пользователя на одной странице.", "Класс не должен скрывать порядок сценария или содержать все assertions."],
    steps: ["Создайте src/pages/login-page.ts с constructor(page).", "Перенесите в класс локаторы полей и submit control.", "Добавьте методы fillCredentials и submit.", "Перепишите один login test через LoginPage; assertions оставьте в тесте."],
    files: ["src/pages/login-page.ts", "tests/ui/login.spec.ts"],
definitionOfDone: ["Тест вызывает LoginPage actions вместо дублирования локаторов.", "LoginPage управляет только страницей входа.", "Assertions конечного состояния остаются в тесте."],
    hints: ["Создавайте Page Object только когда одинаковые действия уже повторяются.", "Передайте Page в constructor и сохраните локаторы этой страницы.", "Сделайте методы действиями с понятными именами; не возвращайте boolean от assertions."],
    commands: ["npm run test -- tests/ui/login.spec.ts"],
  },
  {
    id: "5.2",
    title: "NotesPage и ProfilePage",
    summary: "Разделить действия со списком заметок и профилем пользователя.",
    context: "По мере роста suite один Page Object не должен превращаться в «божественный» класс. Разделение по ответственности упрощает поддержку.",
    theory: ["Один page object описывает один UI-раздел.", "Действия и проверки имеют разные роли: объект выполняет операции, тест формулирует ожидания."],
    steps: ["Выделите повторяющиеся действия Notes list в src/pages/notes-page.ts.", "Выделите действия профиля в src/pages/profile-page.ts.", "Добавьте только действия, которые используются более чем в одном тесте.", "Обновите тесты так, чтобы сценарий читался сверху вниз."],
    files: ["src/pages/notes-page.ts", "src/pages/profile-page.ts", "tests/ui"],
definitionOfDone: ["NotesPage и ProfilePage имеют отдельные зоны ответственности.", "В объектах нет assertion-логики.", "Нет универсального page object с несвязанными методами."],
    hints: ["Сначала найдите повторяющиеся локаторы и действия.", "Сгруппируйте методы по одной странице приложения.", "Оставьте `await expect(...)` в тесте; Page Object пусть выполняет действия или возвращает locator."],
    commands: ["npm run test -- tests/ui"],
  },
  {
    id: "5.3",
    title: "Фикстура registeredUser",
    summary: "Подготовить уникального пользователя декларативно и гарантировать cleanup.",
    context: "Каждый сценарий с авторизацией должен получить собственные данные и завершить их lifecycle независимо от assertions.",
    theory: ["Playwright fixtures внедряют зависимости в тест через аргументы.", "Fixture setup и teardown окружают участок `await use(value)`."],
    steps: ["Создайте tests/fixtures.ts и расширьте базовый test через test.extend.", "Зарегистрируйте новый TestUser через API.", "Передайте user тесту как registeredUser.", "После `await use` удалите созданный аккаунт в finally."],
    files: ["tests/fixtures.ts", "tests/ui/login.spec.ts"],
definitionOfDone: ["Тест получает зарегистрированного пользователя параметром.", "Fixture создаёт уникальные данные для каждого теста.", "Teardown удаляет аккаунт даже при падении теста."],
    hints: ["Fixture — lifecycle вокруг `await use`.", "Сохраните возможность cleanup до начала действий теста.", "Поместите `await use(user)` в try, а DELETE account — в finally."],
    commands: ["npm run test -- tests/ui/login.spec.ts"],
  },
  {
    id: "5.4",
    title: "Фикстуры API-клиентов",
    summary: "Внедрить APIRequestContext и авторизованный API client через fixtures.",
    context: "Создание request context и прокидывание токена вручную в каждом тесте создаёт дублирование и риск утечки секрета.",
    theory: ["Fixture может зависеть от встроенной request fixture.", "Авторизованный клиент — отдельная производная зависимость; token остаётся в памяти."],
    steps: ["Расширьте test фикстурами apiClient и authenticatedApiClient.", "Передайте NOTES_API_URL в client constructor.", "Для authenticated client выполните login и добавьте x-auth-token только внутри клиента.", "Используйте фикстуры вместо прямого request.post в тестах."],
    files: ["tests/fixtures.ts", "src/api/users-api.ts", "src/api/notes-api.ts"],
definitionOfDone: ["API clients внедряются через типизированные fixtures.", "Auth token не логируется и не сохраняется в Git.", "Teardown закрывает контексты и удаляет созданные данные."],
    hints: ["Начните со встроенного request fixture, не создавая глобальный singleton.", "Сделайте authenticated fixture зависимой от API client и user setup.", "Не возвращайте token напрямую в test args."],
    commands: ["npm run test -- tests/api"],
  },
  {
    id: "5.5",
    title: "Изоляция данных по runId и worker",
    summary: "Развести данные параллельных тестов уникальными идентификаторами.",
    context: "Общая Notes API используется параллельными workers и повторными запусками. Похожие title не должны приводить к поиску или удалению чужой записи.",
    theory: ["workerIndex отделяет workers одного процесса.", "runId отделяет независимые запуски; namespace должен различаться и между CI job."],
    steps: ["Добавьте helper runtime namespace из run id и worker index.", "Прокиньте workerInfo/testInfo в фабрику данных.", "Добавьте короткий namespace в email и title каждого ресурса.", "Запустите выбранный suite с несколькими workers и сравните значения."],
    files: ["src/utils/test-data.ts", "tests/fixtures.ts"],
definitionOfDone: ["Сущности разных workers имеют разные суффиксы.", "Независимые прогоны не переиспользуют namespace.", "Cleanup ограничен только ресурсами своего прогона."],
    hints: ["Сначала выберите одну точку формирования namespace.", "workerIndex доступен через workerInfo; runId задайте один раз на запуск.", "Соберите короткий prefix из runId и workerIndex и передавайте его генератору."],
    commands: ["npx playwright test --workers=2"],
  },
  {
    id: "5.6",
    title: "Надёжный teardown",
    summary: "Гарантировать удаление ресурсов при успехе и падении теста.",
    context: "Внешняя SUT сохраняет состояние после завершения процесса. Ошибка проверки не должна оставлять тестовый аккаунт и заметки в общем сервисе.",
    theory: ["Teardown входит в lifecycle fixture и выполняется после use.", "Cleanup должен быть ограничен текущим user/token и обрабатывать повторное удаление."],
    steps: ["Перенесите владение аккаунтом и заметками в fixture lifecycle.", "При необходимости удаляйте заметки, затем аккаунт.", "Поместите cleanup в finally.", "После завершения временного сценария удаления удалите его код."],
    files: ["tests/fixtures.ts", "src/api/notes-api.ts", "src/api/users-api.ts"],
definitionOfDone: ["Созданные данные удаляются при pass/fail.", "Тесты не удаляют записи других пользователей.", "Cleanup errors не раскрывают токен."],
    hints: ["Определите владельца каждого ресурса до создания.", "Разместите `await use(resource)` внутри try/finally.", "Разделите cleanup операции, чтобы ошибка удаления заметки не пропустила удаление аккаунта."],
    commands: ["npm run test -- tests/api"],
  },
  {
    id: "5.7",
    title: "Проверка состояния через Notes API",
    summary: "Проверить состояние заметки через публичный Notes API, не подключаясь к базе данных.",
    context: "Внутренняя база данных не является контрактом Expand Testing. Вместо неё используем официальный Notes API, который видит и само приложение.",
    theory: ["GET /notes/api/notes/{id} возвращает сохранённую заметку.", "API-проверка подтверждает server-side state через публичный контракт."],
    steps: ["Сохраните id заметки после её создания.", "Выполните GET /notes/api/notes/{id} с x-auth-token.", "Сравните title и completed с ожидаемыми значениями.", "Удалите заметку API-запросом в cleanup."],
    files: ["tests/e2e/ui-api-state.spec.ts"],
    definitionOfDone: ["Состояние заметки проверено через Notes API.", "В проекте нет клиента PostgreSQL и DATABASE_URL."],
    hints: ["Передавайте токен только в header x-auth-token.", "Не подключайтесь к базе напрямую.", "Удаляйте только id, созданный текущим тестом."],
    commands: ["npm run test"]
  },
  {
    id: "5.8",
    title: "Подготовка данных через Notes API",
    summary: "Подготовить заметку через Notes API и увидеть её в интерфейсе.",
    context: "API быстро готовит нужные данные, UI подтверждает пользовательский результат. Оба шага используют только Expand Testing.",
    theory: ["POST /notes/api/notes создаёт заметку.", "UI-проверка подтверждает, что заметка доступна пользователю."],
    steps: ["Создайте уникальную заметку POST-запросом.", "Откройте /notes/app авторизованным пользователем.", "Найдите заметку по точному title.", "Удалите её через API в cleanup."],
    files: ["tests/e2e/api-to-ui.spec.ts"],
    definitionOfDone: ["Данные подготовлены Notes API.", "Заметка видна в Notes App."],
    hints: ["Используйте уникальный title.", "Перед UI-проверкой откройте /notes/app.", "Не используйте SQL."],
    commands: ["npm run test"]
  },
  {
    id: "5.9",
    title: "Надёжная очистка через Notes API",
    summary: "Удалить заметки и аккаунт штатным Notes API даже после ошибки теста.",
    context: "Cleanup через публичный API безопаснее прямой работы с базой и не зависит от внутренней схемы приложения.",
    theory: ["finally выполняется после pass и failure.", "Заметки удаляют до удаления аккаунта."],
    steps: ["Сохраните id всех заметок текущего теста.", "Поместите тест в try.", "В finally удалите заметки DELETE /notes/api/notes/{id}.", "Затем удалите аккаунт через users/delete-account."],
    files: ["tests/fixtures.ts"],
    definitionOfDone: ["После теста не остаётся его заметок и аккаунта.", "В проекте нет SQL и прямого доступа к БД."],
    hints: ["Не прекращайте cleanup после первой ошибки удаления.", "Используйте токен текущего пользователя.", "Не удаляйте чужие данные."],
    commands: ["npm run test"]
  },
]);
