import { withModuleId } from "@/lib/course-lesson-builder";

export const moduleFourTasks = withModuleId("4", [
  {
    id: "4.1",
    title: "API-подготовка и UI-проверка",
    summary: "Создать заметку через API и убедиться, что она видна в Notes App.",
    context: "Подготовка данных через API быстрее формы; браузер остаётся средством проверки пользовательского результата.",
    theory: ["Один end-to-end сценарий может использовать несколько каналов взаимодействия.", "API setup сокращает UI-шаги, не заменяя UI assertion."],
    steps: ["Создайте пользователя и заметку через API.", "Авторизуйте UI-контекст тем способом, который доступен на текущем этапе.", "Откройте Notes App и найдите заметку по уникальному title.", "Сравните видимый текст с API payload."],
    files: ["tests/e2e/api-setup-ui-check.spec.ts"],
    definitionOfDone: ["Данные создаются APIRequestContext.", "UI подтверждает заметку через семантический локатор.", "Тест очищает созданный аккаунт после сценария."],
    hints: ["Сохраняйте созданный id и title в переменных теста.", "Отделите API setup от browser assertions.", "Финальная проверка должна искать UI-элемент, а не повторно читать API."],
    checkpoint: "test(e2e): verify API-created note in UI",
    commands: ["npm run test -- tests/e2e/api-setup-ui-check.spec.ts"],
  },
  {
    id: "4.2",
    title: "UI-создание и API-проверка",
    summary: "Создать заметку в интерфейсе и сверить server-side state через API.",
    context: "UI подтверждает пользовательский поток, а API позволяет проверить сохранённые сервером поля без зависимости от оформления карточки.",
    theory: ["UI action и API observation проверяют разные границы системы.", "API assertion должен выполняться после завершения сохранения в UI."],
    steps: ["Войдите через UI и создайте заметку с уникальным маркером.", "Дождитесь подтверждения карточки в UI.", "Получите список/ресурс через Notes API с auth token.", "Найдите запись и сравните её поля с введёнными значениями."],
    files: ["tests/e2e/ui-create-api-verify.spec.ts"],
    definitionOfDone: ["Запись создаётся исключительно UI-действием.", "API подтверждает сохранённое состояние.", "Созданный ресурс удаляется cleanup."],
    hints: ["Дождитесь UI-сигнала сохранения до API-чтения.", "Используйте уникальный title как поиск по результатам API.", "Не проверяйте секретный токен; проверяйте данные заметки."],
    checkpoint: "test(e2e): verify UI-created note via API state",
    commands: ["npm run test -- tests/e2e/ui-create-api-verify.spec.ts"],
  },
  {
    id: "4.3",
    title: "Storage State из API-сессии",
    summary: "Подготовить сессию через API и открыть защищённый UI без формы логина.",
    context: "Повторный UI login в каждом тесте тратит время. Storage state переносит браузерные cookies/local storage, но сам файл содержит секретную сессию.",
    theory: ["storageState сохраняет auth state для browser context.", "Файл сессии — секрет: его нельзя коммитить или загружать в CI artifacts публично."],
    steps: ["Войдите через API и создайте storage state в output/temp каталоге.", "Добавьте путь состояния в .gitignore до использования.", "Создайте browser context со storageState.", "Откройте защищённый раздел и проверьте авторизованную навигацию без формы login."],
    files: ["tests/e2e/storage-state.spec.ts", ".gitignore"],
    definitionOfDone: ["UI открывается в авторизованном контексте без ручного login.", "Состояние создаётся для тестового аккаунта.", "Файл storage state исключён из Git и удаляется после использования."],
    hints: ["Используйте browserContext.storageState({ path }).", "Передайте этот путь в browser.newContext({ storageState }).", "Добавьте точный путь в .gitignore и проверьте его git check-ignore."],
    checkpoint: "test(e2e): use storage state from API for UI tests",
    commands: ["npm run test -- tests/e2e/storage-state.spec.ts", "git check-ignore playwright/.auth/user.json"],
  },
  {
    id: "4.4",
    title: "Массовые данные и фильтрация",
    summary: "Создать набор заметок через API и проверить поиск в UI.",
    context: "Большой набор данных эффективнее создавать API, а фильтрацию проверять через тот интерфейс, которым пользуется человек.",
    theory: ["Цикл подготовки данных должен сохранять id для cleanup.", "Поиск проверяется уникальными значениями и отсутствием посторонних результатов."],
    steps: ["Сгенерируйте несколько заметок с уникальными title.", "Создайте их через API в одном user scope.", "Откройте Notes App и выполните поиск по одному маркеру.", "Проверьте совпадения и восстановление списка после очистки поиска."],
    files: ["tests/e2e/api-data-ui-filter.spec.ts"],
    definitionOfDone: ["Массовая подготовка выполняется API.", "UI фильтрует целевую запись без ложных совпадений.", "Все созданные записи удаляются в teardown."],
    hints: ["Сохраняйте ответы каждого create запроса.", "Пусть title отличаются одним уникальным маркером.", "Проверяйте полные заголовки найденной и исключённой заметки."],
    checkpoint: "test(e2e): test UI search with API-generated data",
    commands: ["npm run test -- tests/e2e/api-data-ui-filter.spec.ts"],
  },
  {
    id: "4.5",
    title: "UI delete и API 404",
    summary: "Удалить запись в UI и подтвердить отсутствие ресурса через API.",
    context: "Исчезновение карточки подтверждает UI, а 404 по тому же id — что удаление дошло до backend.",
    theory: ["Кросс-слойная проверка сопоставляет одну сущность по id.", "Ожидаемая ошибка чтения удалённого ресурса должна быть конкретным 404."],
    steps: ["Создайте заметку и сохраните её id.", "Удалите её через UI и дождитесь исчезновения карточки.", "Запросите тот же id через API.", "Проверьте status 404 и выполните cleanup пользователя."],
    files: ["tests/e2e/ui-delete-api-check.spec.ts"],
    definitionOfDone: ["Удаление инициируется UI.", "UI-карточка скрыта, API возвращает 404 для того же id.", "Cleanup гарантирован."],
    hints: ["Не ищите resource id из другого пользователя.", "Дождитесь UI исчезновения до API-запроса.", "Проверьте ровно ожидаемый 404, не любое response.ok() === false."],
    checkpoint: "test(e2e): verify UI deletion via API 404 response",
    commands: ["npm run test -- tests/e2e/ui-delete-api-check.spec.ts"],
  },
  {
    id: "4.6",
    title: "Теги и выборочный запуск",
    summary: "Сгруппировать тесты тегами и запускать набор через grep.",
    context: "Smoke, API, UI и e2e проверки требуют разной длительности и частоты запуска. Теги позволяют выбрать набор без копирования тестов.",
    theory: ["Playwright grep фильтрует тесты по имени/описанию.", "Теги в названии должны быть единообразными и не смешивать тип проверки со статусом теста."],
    steps: ["Добавьте теги @smoke, @api, @ui и @e2e в названия подходящих тестов.", "Добавьте npm scripts для запуска каждого набора через --grep.", "Запустите каждый набор и проверьте список выбранных тестов.", "Сохраните понятный порядок тегов и имен."],
    files: ["tests/**/*.spec.ts", "package.json"],
    definitionOfDone: ["Теги отражают тип сценария.", "Команды grep запускают ожидаемый набор.", "Общие тесты не запускаются дважды из-за случайных тегов."],
    hints: ["Сначала перечислите тесты, входящие в каждый набор.", "Добавляйте тег в title теста, а не в код ассерта.", "Для npm script передайте `--grep @api` после `playwright test`."],
    checkpoint: "chore(tests): add tags for smoke, api, ui, and e2e suites",
    commands: ["npm run test -- --grep @smoke", "npm run test -- --grep @api"],
  },
]);